
[functions.clean-inactive-rooms]
enabled = true
verify_jwt = true
import_map = "./functions/clean-inactive-rooms/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/clean-inactive-rooms/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/clean-inactive-rooms/*.html" ]
